# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: 1.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-07-07 16:29+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: Daniel Kjellid <daniel@flis.no>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: NO\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: aria/api_auth/services.py:103
msgid ""
"Wrong username or password. Note that you have to separate between lowercase "
"and uppercase characters."
msgstr ""
"Feil brukernavn eller passord. Merk at du må skille mellom store og små "
"bokstaver."

#: aria/api_auth/services.py:121 aria/api_auth/services.py:144
msgid "Refresh token provided is invalid."
msgstr "Oppdateringsnøkkelen gitt er ugyldig."

#: aria/api_auth/services.py:124
msgid "Test"
msgstr ""

#: aria/api_auth/services.py:125 aria/api_auth/services.py:147
msgid "Token payload is invalid."
msgstr "Nøkkelens nyttelast er ugyldig."

#: aria/api_auth/services.py:130
msgid "Issued user in refresh token does not exist."
msgstr "Bruker i oppdateringsnøkkel eksisterer ikke."

#: aria/api_auth/services.py:155
msgid "Refresh token provided does not exist."
msgstr "Oppdateringsnøkkelen eksisterer ikke."

#: aria/kitchens/endpoints/public.py:49
msgid "Kitchen with provided slug does not exist"
msgstr "Fant ikke kjøkken med gitt slug"

#: aria/products/endpoints/public.py:32
msgid "Product with provided slug does not exist"
msgstr "Fant ikke produktet med gitt slug"

#: aria/users/endpoints/public.py:56 aria/users/endpoints/public.py:100
msgid "User does not exist."
msgstr "Brukeren eksisterer ikke."

#: aria/users/models.py:345
msgid "Email is already verified, unable to send verification email."
msgstr "Kontoen er allerede verifisert, kunne ikke sende verifiserings e-post."

#: aria/users/services.py:41
msgid "User with email already exists."
msgstr "Det finnes allerede en konto med den e-posten."

#: aria/users/services.py:162 aria/users/services.py:190
msgid "Unable to find user with provided uid."
msgstr "Fant ikke brukeren med gitt uid."

#: aria/users/services.py:166
msgid "Account is already verified."
msgstr "Kontoen er allerede verifisert."

#: aria/users/services.py:171 aria/users/services.py:196
msgid "Token is invalid, please try again."
msgstr "Nøkkelen er ugyldig, vennligst prøv igjen."
